trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  BuildConfig: "Release"
  RuntimeId: "linux-x64"
  ProjectName: "CodingEventsAPI"
  ArtifactOutputDir: "$(Build.StagingDirectory)/bin"

stages:
  - stage: BuildStage
    jobs:
      - job: BuildForLinux
        displayName: Create Linux Artifact
        steps:
          - task: DotNetCoreCLI@2
            displayName: "Publish [config $(BuildConfig)] [runtime $(RuntimeId)]"
            inputs:
              command: publish
              arguments: "-c $(BuildConfig) -r $(RuntimeId) -o $(ArtifactOutputDir) -p:PublishSingleFile=true"
              projects: "**/$(ProjectName).csproj"
          - script: ls -l "$(ArtifactOutputDir)"
      - job: PublishLinuxArtifact
        dependsOn: BuildForLinux
        displayName: Publish Linux Executable Artifact
        steps:
          - script: ls -l "$(ArtifactOutputDir)"
          - publish: "$(ArtifactOutputDir)/$(ProjectName).zip"
            artifact: "$(ProjectName)"

  - stage: DeployStage
    dependsOn: BuildStage
    variables:
      EnvName: "linux"
      VmName: "student-linux"
    jobs:
    - deployment: deploy
      displayName: Linux Deploy
      # alternatively
      # environment: "$(EnvName).$(VmName)"
      # substitution isnt working here?
      # environment:
      #   name: "$(EnvName)"
      #   resourceName: "$(VmName)"
      #   resourceType: VirtualMachine
      environment:
        name: "linux"
        resourceName: "student-linux"
        resourceType: VirtualMachine
      strategy:
        runOnce:
          preDeploy:
            steps:
              - download: current
                artifact: "$(ProjectName)"
              - script: echo "downloaded artifact"
              - script: ls -l "$(Pipeline.Workspace)"
          deploy:
            steps:
              - script: echo "executing artifact at $(Pipeline.Workspace)/$(ProjectName)"
              - script: './$(Pipeline.Workspace)/$(ProjectName)'
                

