# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# what image the build files are create on, not what they will be deployed to
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

# straightforward approach that mirrors what's student have seen
# pros: very straightforward, very concise
# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

# less straightforward, but is extensible, and more realistic to what they will see in the future (assumption)
# ask engineers what is the MS preferred way of writing YAML pipelines
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: build
    arguments: --configuration $(buildConfiguration)